config/routes.rb
Rails.application.routes.draw do

  get '/search', to: 'main#search'

  root 'pages#home'
resources :articles
  get '/about', to: 'pages#about'
get '/signup',  to: 'users#new'

get '/login',  to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'
resources :users, except: [:new]
resources :categories, except: [:delete]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
  class Article < ActiveRecord::Base
     belongs_to :user
     has_many :article_categories
     has_many :categories, through: :article_categories
     validates :title, presence: true , length: {minimum: 3, maximum: 50}
     validates :description, presence: true
     validates :user_id , presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action  :set_article , only: [:edit,:update,:destroy,:show]
before_action :require_user, except: [:index, :show]
before_action :require_same_user, only: [:edit, :update, :destroy]
def index
  @articles = Article.paginate(page: params[:page],per_page: 5)
end

def new
@article = Article.new
end

def create
  @article = Article.new(article_params)
    @article.user = current_user
   if @article.save
          flash[:success]= "Article was successfully created"
          redirect_to article_path(@article)
   else
    #  flash[:alert] = @article.errors.full_messages
     render 'new'
   end
# we need to white list the articles params
end

def show
  @article = Article.includes(:comments).find(params[:id])
  @comment = Comment.new
end

def destroy
  @article.destroy
  flash[:danger] = "Article deleted successfully"
  redirect_to articles_path

  #code
end

def edit
end

def update
 if @article.update(article_params)
   flash[:success] = "Article has been successfully updated"
   redirect_to article_path(@article)
 else
   render 'edit'
 end
end

private

  def require_same_user
      if current_user != @article.user and !current_user.admin?
       flash[:danger] = "You can only edit or delete your own articles"
     redirect_to root_path
  end
  end


 def set_article
   @article = Article.find(params[:id])
 end


def article_params
  params.require(:article).permit(:title,:description,category_ids: [])
end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code,language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)
    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/articles/_article.html.erb
 <% obj.each do |article| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2" >
         <div class="well well-lg">
           <div class="article-title">
   <%= link_to article.title, article_path(article) %>
      </div>

      <div class="article-body">
          <div class="article-meta-details">
             <small> Created by: <%= article.user.username if article.user %>,
               <%= time_ago_in_words(article.created_at) %> ago,
               last updated: <%= time_ago_in_words(article.updated_at) %> ago
           </small>
       </div>
     </div>

  <% if article.categories.any? %>
  <p>  Categories: <%= render article.categories  %> </p>

  <% end %>


  <%if logged_in? && (current_user == article.user || current_user.admin?) %>


       <div class="article-actions">
       <%= link_to "Edit this article" , edit_article_path(article),class: "btn btn-primary btn-xs" %>
       <%= link_to "Delete this Article" , article_path(article), method: :delete,data: {confirm: "Are you sure?"} ,class: "btn btn-danger btn-xs" %>
        </div>

  <% end %>

      </div>
    </div>
  </div>

<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div id="row">
  <div class="col-xs-12">
            <%= form_for(@article, :html => {class: "form-horizontal", row: "form"}) do |f| %>
     <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :title %>
            </div>
            <div class="col-sm-8">
            <%= f.text_field :title, class: "form-control",placeholder: "Title of Article", autofocus: true%>
          </div>
    </div>


    <div class="form-group">
       <div class="control-label col-sm-2">
              <%= f.label :description %>
            </div>
            <div class="col-sm-8">
              <%=f.text_area :description,rows: 10, class: "form-control", placeholder: "Body of article"%>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%=f.submit class: "btn btn-primary btn-large"%>
              </div>
            </div>

            <div class="form-group">
              <div class="row">

              <div class="col-sm-offset-2 col-sm-8">
                  <%=f.collection_check_boxes :category_ids, Category.all, :id ,:name do |cb|%>
                    <% cb.label(class: "checkbox-inline input_checkbox"){cb.check_box(class: "check_box") + cb.text} %>
                  <% end %>
                </div>
              </div>
            </div>



            <% end %>
<div class="col-xs-4 col-xs-offset-4">
            <%= link_to "[ Cancel Request and return to Articles Listing ]" , articles_path %>
</div></div></div>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit existing article</h1>
<!-- form_for prefills the database with existing details -->

<%= render 'form' %>

app/views/articles/index.html.erb

<h1 class="text-center">Listing All articles</h1>
<div class="text-center">
<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
</div>
<%= render 'article', obj: @articles %>
<div class="text-center">
<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center">Create an article</h1>

 <%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">
<%= @article.title %>
</h2>

<div class="well col-xs-8 col-xs-offset-2">


<% if @article.user %>
<ul class="listing">
  <div class="row text-center">
    <div class="col-md-4 col-md-offset-4">
     <li> Created by:</li>
      <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
       <li class="article-title"
           <%= link_to @article.user.username, user_path(@article.user) %>
      </li>
      <li><small>  <%= pluralize( @article.user.articles.count , "article") if @article.user.articles %>  </small></li>
    </div>
  </div>
</ul>
<% end %>


<h4 class="center desc">  </h4>
<hr>
<%=  markdown(@article.description) %>

  <% if @article.categories.any? %>

  <p> Categories:  <%= render @article.categories %>

  <% end %>



<div class="article-actions">
 <% if logged_in? && (current_user == @article.user || current_user.admin? ) %>
<%= link_to "Edit this article" , edit_article_path(@article),class: "btn btn-primary btn-md" %>
<%= link_to "Delete this Article" , article_path(@article), method: :delete,data: {confirm: "Are you sure?"} ,class: "btn btn-danger btn-md" %>
<% else %>
 <%= link_to "View all Articles" , articles_path,class: "btn btn-success btn-md" %>
 <% end %>
</div>
</div>