config/routes.rb
Rails.application.routes.draw do

  get '/search', to: 'main#search'

  root 'pages#home'
resources :articles
  get '/about', to: 'pages#about'
get '/signup',  to: 'users#new'

get '/login',  to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'
resources :users, except: [:new]
resources :categories, except: [:delete]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :article_categories
has_many :articles, through: :article_categories
validates :name, presence: true,length: { minimum: 3,maximum: 25}
validates :name, uniqueness: true, case_sensitive: false
# validates_uniqueness_of :name ,case_sensitive: false
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index,:show]
      def index
      @categories = Category.paginate( page: params[:page],per_page: 5)
      end

      def new
      @category = Category.new
      end

      def show
         @category = Category.find(params[:id])
         @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
       end

      def create
        @category = Category.new(category_params)
          if @category.save

           flash[:success] = "Category created Successfully"
              redirect_to categories_path
          else
               render 'new'
          end
      end

def edit
@category = Category.find(params[:id])
end

def update
  @category = Category.find(params[:id])
       if @category.update(category_params)
       flash[:success] = "Category name has been successfully updated"
       redirect_to category_path(@category)
       else
       render 'edit'
       end
end


private
        def category_params
        params.require(:category).permit(:name)
        end

        def require_admin
          if !logged_in? || (logged_in? and !current_user.admin?)
            flash[:danger]= "Only admins can perform this action"
              redirect_to categories_path
          end
        end

end

app/views/categories/_category.html.erb
<span class="badge badge_design"> <%= link_to category.name,category_path(category) %> &nbsp </span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
    <%= form_for(@category, :html => {class: "form-horizontal", row: "form"}) do |f| %>
<div class="form-group">
<div class="control-label col-sm-2">
    <%= f.label :name %>
    </div>
    <div class="col-sm-8">
    <%= f.text_field :name, class: "form-control",placeholder: "Category Name", autofocus: true%>
  </div>
</div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <%=f.submit "Create Category",class: "btn btn-primary btn-large"%>
      </div>
    </div>


    <% end %>
<div class="col-xs-4 col-xs-offset-4">
    <%= link_to "[ Cancel Request and return to Articles Listing ]" , articles_path %>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center"> EDIT THIS CATEGORY</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center">
  Listing all Categories
</h1>
<div class="align-center text-center">
  <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
 <% @categories.each do |category| %>
    <ul class="listing ">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title">
             <%= link_to "#{category.name}", category_path(category) %>
              <li><small> <%= pluralize(category.articles.count, 'article') %> </small></li>
          </li>
        </div>
      </div>
    </ul>
    <% end %>
    <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center"> Create a new Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb


<h1 class="text-center"><%= "Category:" + @category.name %></h1>
<div class="text-center">

<% if logged_in? && current_user.admin? %>
  <div class="row">
    <div class="col-xs-offset-6 col-xs-6">
      <span class="badge badge_design2 "><%= link_to "Edit Category", edit_category_path(@category) %> </span>
    </div>
  </div>
  <div class="row">
    <p></p>
  </div>
<% end %>
<%= will_paginate @category_articles, renderer: BootstrapPagination::Rails %>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div class="text-center">
<%= will_paginate @category_articles, renderer: BootstrapPagination::Rails %>
</div>